import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import LoginBtn from '@/component/LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogOutBtn from '@/component/LogOutBtn';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  // 서버컴포넌트,서버기능안에서 사용가능, 로그인 유저정보관련된기능
  let session = await getServerSession(authOptions);

  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='navbar'>
          <Link href='/' className='logo'>
            AppleForum 🍎
          </Link>
          {session ? (
            <div className='userInfo-wrap'>
              <span className='user-name'>{session.user.name}</span> &nbsp;
              <LogOutBtn />
            </div>
          ) : (
            <LoginBtn user={session.user} />
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
